@extends('layouts.cliente')

@section('title', 'Calendario de Turnos')

@section('content')
<div class="space-y-6">
    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
            <h1 class="text-2xl font-bold text-white">Calendario de Turnos</h1>
            <p class="text-gray-400 mt-1">Visualiza los turnos agendados para tus vehículos (solo lectura)</p>
        </div>
    </div>

    <!-- Leyenda -->
    <div class="bg-zinc-800 border border-zinc-700 rounded-lg p-4">
        <div class="flex flex-wrap gap-4 text-sm">
            <div class="flex items-center gap-2">
                <span class="w-3 h-3 rounded-full bg-blue-500"></span>
                <span class="text-gray-300">Turno Service</span>
            </div>
            <div class="flex items-center gap-2">
                <span class="w-3 h-3 rounded-full bg-orange-500"></span>
                <span class="text-gray-300">Turno Mecánico</span>
            </div>
        </div>
    </div>

    <!-- Calendar -->
    <div class="bg-zinc-800 border border-zinc-700 rounded-lg overflow-hidden">
        <!-- Calendar Controls -->
        <div class="p-4 border-b border-zinc-700 flex items-center justify-between">
            <button onclick="changeMonth(-1)" class="p-2 text-gray-400 hover:text-white hover:bg-zinc-700 rounded-lg transition">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg>
            </button>
            <h3 id="calendar-title" class="text-lg font-semibold text-gray-100"></h3>
            <button onclick="changeMonth(1)" class="p-2 text-gray-400 hover:text-white hover:bg-zinc-700 rounded-lg transition">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
            </button>
        </div>

        <!-- Days of week header -->
        <div class="grid grid-cols-7 bg-zinc-900">
            <div class="px-2 py-3 text-center text-xs font-medium text-gray-400 uppercase">Lun</div>
            <div class="px-2 py-3 text-center text-xs font-medium text-gray-400 uppercase">Mar</div>
            <div class="px-2 py-3 text-center text-xs font-medium text-gray-400 uppercase">Mié</div>
            <div class="px-2 py-3 text-center text-xs font-medium text-gray-400 uppercase">Jue</div>
            <div class="px-2 py-3 text-center text-xs font-medium text-gray-400 uppercase">Vie</div>
            <div class="px-2 py-3 text-center text-xs font-medium text-gray-400 uppercase">Sáb</div>
            <div class="px-2 py-3 text-center text-xs font-medium text-gray-400 uppercase">Dom</div>
        </div>

        <!-- Calendar Grid -->
        <div id="calendar-grid" class="grid grid-cols-7 border-t border-zinc-700">
            <!-- Days will be generated by JS -->
        </div>
    </div>

    <!-- Event Detail Modal (read-only) -->
    <div id="event-detail-modal" class="hidden fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4">
        <div class="bg-zinc-900 rounded-lg w-full max-w-md border border-zinc-700">
            <div class="p-6">
                <div class="flex justify-between items-center mb-4">
                    <h3 class="text-lg font-semibold text-gray-100">Detalle del Turno</h3>
                    <button onclick="document.getElementById('event-detail-modal').classList.add('hidden')" class="text-gray-400 hover:text-gray-200">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                    </button>
                </div>
                <div id="event-detail-content" class="space-y-3 text-sm"></div>
            </div>
        </div>
    </div>
</div>

<script>
    const EVENTS_URL = '{{ route("client.calendario.eventos") }}';
    let currentDate = new Date();
    let events = [];
    const monthNames = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];

    function changeMonth(offset) {
        currentDate.setMonth(currentDate.getMonth() + offset);
        loadEvents();
    }

    function loadEvents() {
        fetch(EVENTS_URL, {
            headers: { 'Accept': 'application/json', 'X-Requested-With': 'XMLHttpRequest' }
        })
        .then(r => r.json())
        .then(data => {
            events = data;
            renderCalendar();
        })
        .catch(err => {
            console.error('Error loading events:', err);
            renderCalendar();
        });
    }

    function renderCalendar() {
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();
        document.getElementById('calendar-title').textContent = monthNames[month] + ' ' + year;

        const grid = document.getElementById('calendar-grid');
        grid.innerHTML = '';

        const firstDay = new Date(year, month, 1);
        // Monday = 0
        let startDay = firstDay.getDay() - 1;
        if (startDay < 0) startDay = 6;

        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const today = new Date();

        // Total cells
        const totalCells = Math.ceil((startDay + daysInMonth) / 7) * 7;

        for (let i = 0; i < totalCells; i++) {
            const dayNum = i - startDay + 1;
            const cell = document.createElement('div');
            cell.className = 'min-h-[80px] md:min-h-[100px] border-b border-r border-zinc-700 p-1';

            if (dayNum >= 1 && dayNum <= daysInMonth) {
                const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(dayNum).padStart(2, '0')}`;
                const isToday = today.getFullYear() === year && today.getMonth() === month && today.getDate() === dayNum;

                cell.innerHTML = `<div class="text-xs font-medium ${isToday ? 'text-blue-400 font-bold' : 'text-gray-400'} mb-1">${dayNum}</div>`;

                if (isToday) {
                    cell.classList.add('bg-blue-900/10');
                }

                // Find events for this day
                const dayEvents = events.filter(e => {
                    const eDate = new Date(e.start);
                    return eDate.getFullYear() === year && eDate.getMonth() === month && eDate.getDate() === dayNum;
                });

                dayEvents.forEach(ev => {
                    const evDiv = document.createElement('div');
                    evDiv.className = 'text-xs p-1 mb-0.5 rounded cursor-pointer truncate';
                    evDiv.style.backgroundColor = ev.color + '30';
                    evDiv.style.color = ev.color;
                    evDiv.style.borderLeft = '3px solid ' + ev.color;
                    evDiv.textContent = ev.title;
                    evDiv.onclick = () => showEventDetail(ev);
                    cell.appendChild(evDiv);
                });
            } else {
                cell.classList.add('bg-zinc-900/50');
            }

            grid.appendChild(cell);
        }
    }

    function showEventDetail(ev) {
        const content = document.getElementById('event-detail-content');
        const props = ev.extendedProps || {};
        const date = new Date(ev.start);
        const dateFormatted = date.toLocaleDateString('es-AR', { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' });

        content.innerHTML = `
            <div class="bg-zinc-800 p-3 rounded-lg">
                <div class="text-xs text-gray-400">Tipo</div>
                <div class="text-gray-200 font-medium">${props.tipo_servicio === 'turno_service' ? 'Turno Service' : 'Turno Mecánico'}</div>
            </div>
            <div class="bg-zinc-800 p-3 rounded-lg">
                <div class="text-xs text-gray-400">Vehículo</div>
                <div class="text-gray-200 font-medium">${props.vehiculo || 'N/A'}</div>
            </div>
            <div class="bg-zinc-800 p-3 rounded-lg">
                <div class="text-xs text-gray-400">Taller</div>
                <div class="text-gray-200 font-medium">${props.taller || 'N/A'}</div>
            </div>
            <div class="bg-zinc-800 p-3 rounded-lg">
                <div class="text-xs text-gray-400">Fecha y Hora</div>
                <div class="text-gray-200 font-medium">${dateFormatted}</div>
            </div>
            <div class="bg-zinc-800 p-3 rounded-lg">
                <div class="text-xs text-gray-400">Estado</div>
                <div class="text-gray-200 font-medium capitalize">${ev.estado || 'N/A'}</div>
            </div>
            <div class="mt-2 p-2 bg-amber-900/20 border border-amber-800/30 rounded text-amber-400 text-xs flex items-center gap-2">
                <svg class="w-4 h-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                Calendario de solo lectura. Contacte al administrador para modificar turnos.
            </div>
        `;
        document.getElementById('event-detail-modal').classList.remove('hidden');
    }

    // Load on init
    loadEvents();
</script>
@endsection
